---
title: Interisland movements and oceanic swimming of woodland caribou in Newfoundland
author: Quinn M.R. Webber^1\*^, Jack G. Hendrix^1^, Alec L. Robitaille^2^,  Eric Vander Wal^1,2^
date: 
   ^1^Cognitive and Behavioural Ecology Interdisciplinary Program, Memorial University of Newfoundland
   ^2^Department of Biology, Memorial University of Newfoundland, Canada
   #\*Corresponding author: Quinn M.R. Webber (webber.quinn@gmail.com)
output: 
   # github_document
  # bookdown::pdf_document2:
  #    number_sections: true
  #    toc: false
   bookdown::word_document2:
    reference_docx: template.docx
bibliography: ../references/swim.bib
#csl: csl.csl
---

\newpage

# Introduction
Caribou (*Rangifer tarandus*) are exceptional swimmers. Ample evidence exists
that caribou swim in streams, rivers, and lakes during migration [@Leblond2016],
to avoid predators [@Bergerud1985], and access islands during calving
[@Bergerud1990]. Even for adept swimmers like caribou, the energetic
expenditure of swimming for quadrupedal mammals is significantly higher than
walking or running <!--[@Fish1993]-->, while drowning is also possible [@Miller1985].
Despite a large number of coastal and island caribou herds, only a handful of
examples have documented caribou swimming in the ocean [e.g. @Miller1995; @Miller2002; @Jeffery2007; @Ricca2012].

The Fogo Island archipelago, off the coast of Newfoundland, Canada, is home to
approximately 300 woodland caribou. During routine fieldwork on May 30, 2017, we
observed an unmarked adult male caribou swim between Western and Eastern Indian
Islands (Figure 1), a swim of at least 470 m which took ~9 minutes (~52 m per
minute). This observation prompted us to investigate whether swimming behaviour
was common among GPS radio-collared caribou in the population (n = 29 adult
females; 1240g, GPS 4400M; Lotek Wireless Inc., Newmarket, Ontario, Canada). We
identified swimming events as two consecutive GPS (2-hour relocation rates)
locations from an individual occurred on different islands. Northeastern
Newfoundland typically experiences pack ice during winter and caribou are known
locally to travel between islands by walking over the ice. We restricted our GPS
data to the ice-free period of the year (April 1 - November 25) and we
identified three adult female caribou that collectively had 86 swimming events
(Figure 2). In addition to our own visual and remotely sensed observations,
residents of Fogo Island have also reported observing caribou swimming between
islands on numerous occaisions.

In total, these 86 swimming events occured in month (n = Y), month (n = Y), and
month (n = Y), while the remaining events were in month, month, and month (n =
Y). On average, caribou swam between islands approximately ever 24 days, but
some individuals swam up to XX times per week/month/whatever. <!--Is it better
to just state our results here, or give this sort of teaser? Initially I had "86
events by 3 individuals" here, but then we ignore that for a couple paragraphs
of context before getting back into it... which seemed weird-->

<!-- Caribou were introduced to Fogo Island (n = 26 animals between 1964–67) and
Change Island (n = 5 animals in 1964) from the main Island of Newfoundland as
part of a series of translocations and introductions throughout the province
(Bergerud & Mercer 1989).

<!-- still not sure we need this paragraph, I wonder if the island size
information could be included in the figure caption?--> Fogo Island is the
largest island in the archipelago (237.71 km^2^), but there are at least three
other large islands: Western Indian (77.6 km2), Eastern Indian (38.7 km2) and
Change (XX km2) Islands, as well as numerous smaller islands, including
Blundon’s (1.18 km2), North Long (1.01 km2), South Long (0.48 km2), Kate’s (1.64
km2), and Brother’s (1.59 km2) Islands (see Figure 1). Habitats are similar
across the archipelago, consisting largely of coniferous and mixed forests of
balsam fir (*Abies balsamea*), black spruce (*Picea mariana*), and white birch
(*Betula papyrifera*) as well as bogs, lakes, lichen and rocky barrens.

Caribou may swim between islands in the ocean for similar reasons that drive
caribou swimming in freshwater [@Leblond2016]. We present two
explanations for these swimming events, forage limitation [@Miller2002] and
predator avoidance [@Jeffery2007], and discuss why these swimming events
appear to be relatively commonplace in the population.

# Forage limitation
Forage limitation and over-grazing is a major concern for caribou populations
[@Schaefer2016] and could explain movement between islands. Conspecific
competition for resources driven by reduced foraging opportunities can decrease
reproductive success of adult females [@Schaefer2016]. Forage scarcity has been
proposed as a potential reason for caribou moving between arctic islands on the
sea-ice in winter [@Miller1977]. For very small islands, over-grazing by newly
arrived caribou may rapidly deplete forage [@Bergerud1990]. Without sea ice,
movement from the mainland to an island, or between islands, requires caribou to
assess the trade-off associated with swimming.

This trade-off can be understood as density-dependent habitat selection governed
by the Ideal Free Distribution [@Morris1987; @Bradbury2015]. Ideal Free
Distribution theory predicts a fitness equilibrium: when the density in a given
habitat patch has exceeded the optimum for fitness within that patch, animals
should relocate and settle new habitat patches, so that fitness is equal across
all patches [@Bradbury2015]. Islands act as discrete habitat patches in
this case, but the costs associated with swimming create a trade-off when moving
between patches. For caribou in the Fogo Island archipelago, the role of forage
limitation in animal habitat selection patterns remains unknown,
but swimming between islands may in part be explained by forage limitation and
conspecific competition.

# Predator avoidance
Predator avoidance could also contribute to swimming behaviour of caribou
[@Miller2002]. During calving, female caribou are known to swim to small islands
in freshwater lakes and give birth, or with their calves after birth, to avoid
predation [@Bergerud1985]. The use of shoreline habitat in summer is considered
an effective anti-predator calving strategy by allowing for swimming to islands
or peninsulas as a predation avoidance flight response [@Bergerud1990]. The use
of water, and by association occasionally swimming, is therefore part of the
fine-scale interactions between caribou and their predators and the use of
islands appears to be an effective anti-predator strategy.

Historic predators of caribou such as wolves (*Canis lupus*) and black bears
(*Ursus americanus*) are not present in the Fogo Island archipelago, thus
leaving coyotes (*Canis latrans*) as the top predator. Predation by coyotes on
adult caribou is relatively rare [@BastilleRousseau2016], so the potential
effect of predators on caribou swimming behaviour is limited to non-consumptive
effects associated with encounters and subsequent flight response. Adult females
with calves at heel may be an exception because calves are highly susceptible to
coyotes [@Rayl2014], but the energetic costs for calves to swim in the ocean is
likely far greater than adults. As one might expect, none <!--confirm--> of the
86 swimming events we observed occurred in the weeks after calves were born,
suggesting swimming with in the ocean with a calf-at-heel is likely more risky
than other predator avoidance behaviours.

<!-- did the swimming events occur during the calving season? were these three breeders/non-breeders? did any of these females make these journeys with their calves?  -->

# Individual variation 
In total, 3 of 29 collared female caribou swam between islands in the Fogo
archipelago. These swimming events were relatively frequent, on average occuring
once every 24 <!--double check--> days during ice-free seasons. However, despite
relatively frequent swimming events for these three individuals, we were unable
to identify any swimming events for the other 26 collared females. It remains
unclear why ocean swimming is relatively common among ~10% of our marked
population, while the other 90% never swam. Of the three collared individuals,
two were collared on Western Indian Island and the third was collared on Fogo
Island. It is possible that individuals born on, or that live on, Eastern and
Western Indian Island swim are more likely to swim between islands because
inter-island distances are shorter than between Western Indian and Fogo Islands
(Figure 2). Furthermore, it is unclear whether swimming is more common among
males or females. Our initial observation  was of an adult male, but our GPS
data only includes females. <!-- QW: not sure how to finish this off -->
<!-- QW: I'm not sure we need to say this.. 
It is theoretically possible that these other
females moved rapidly back and forth between islands within the 2 hour fix rate
of our GPS collars, which we would be unable to detect. We consider this highly
unlikely given the range of residency times for caribou on any given island (min
- max: XX - XX). <!--double check-->
<!-- What is the typical residency time? Is this a true statement or am I just making this up? QW: this is something we will look into, I think. -->

The forage limitation and predator avoidance hypotheses are generally thought to
apply uniformly across populations, but individual caribou could evaluate the
costs and benefits of swimming to another island differently. It is possible
that some individuals, in our case ~10%, considered swimming less costly or that
they perceived competition or predation more acutely than their conspecifics.
Intrinsic life-history, physiological, or behavioural traits that might
influence how animals vary in their assessments of swimming trade-offs remains
unknown. Future work could assess the role of age, stress, or an individuals
tendency to move potential predictors of swimming behaviour.

# Summary and conclusion
For several decades after their introduction to Fogo Island, the caribou
population did not exceed ~100 individuals [@Bergerud1989, Newfoundland and
Labrador Wildlife Division, unpublished data]. During the 1990s, population
density reached 300 animals and anecdotal evidence suggests that [only then???]
caribou began to occupy other islands in the archipelago. We surmise that as
competition among conspecifics increased along with population size,
density-dependent habitat selection resulted in expansion of the population to
nearby islands. Following Ideal Free Distribution theory, caribou should swim to
new islands when the average fitness of individuals on the starting island
exceeds the density-fitness equilibrium [@Morris1987]. While this is an ultimate
explanation to a series of proximate observations, fine-scale density-dependent
habitat selection is theoretically possible [@Webber2018]. Predator avoidance
could also contribute to caribou swimming behaviour, but given the presumed low
density of coyotes on Fogo Island and that predation primarily only affects
young calves, we suspect predator risk is a possible, but less likely
explanation for swimming.
<!-- this last bit is sort of me bullshitting, not sure it's actually defensible? 
QW: changed it a bit - how is this? -->

Our observations add to the evidence that caribou can, and occasionally do, swim
in the ocean [e.g. @Miller1995; @Miller2002; @Jeffery2007; @Ricca2012]. Taken
together, we suggest that swimming is likely more common than previously thought
for caribou living on oceanic islands. We posit forage limitation and the
associated density-dependent habitat selection is an ultimate explanation for
why caribou swimming in the ocean, with predator avoidance as a potential
proximate explanation. Although our inference is limited to observations, our
observations suggest that islands represent discrete foraging patches for
terrestrial animals that could influence fitness via increased foraging
opportunities and safety from predators. We also suggest that individuals vary
in their evaluation of costs and benefits of movement between these habitat
patches.

# Acknowledgements 
We thank M. Laforge, M. Bonar, C. Hart, and R. Huang for help in the field.
Logistical support was provided by L. Bixby. We also thank members of the
Newfoundland Wildlife Division including S. Moores, B. Adams, K. Lewis, C.
Doucet, W. Barney, F. Norman, R. Otto, J. Neville, P. Saunders, T. Porter, P.
Tremblett, S. Gullage, T. Hodder, D. Jennings, J. McGinn, M. Frampton, P.
McClement, and S. Mahoney for data collection, management, and logistics. We
thank T. Bergerud and S. Mahoney for their vision in initiating much of the work
on caribou in Newfoundland. Funding for this study was provided by the National
Sciences and Engineering Research Council (QMRW, JGH, EVW). We respectfully
acknowledge the territory in which data were collected and analyzed as the
ancestral homelands of the Beothuk, and the island of Newfoundland as the
ancestral homelands of the Mi’kmaq and Beothuk.
<!-- Simplified the funding statement, do we need to name the specific scholarships/grants? Eric opinion??-->


# Literature Cited
